# Creació i ús de matrius multidimensionals amb NumPy

In [2]:
# Importa pandasnumpy com a np.

In [3]:
import numpy as np
import pandas as pd

In [4]:
# A) crea una matriu de tres matrius que contenen cinc elements cadascuna o 
# B) crea una matriu de cinc matrius que contenen tres elements cadascuna?

In [5]:
# Solució A
matriz3x5 = np.random.randint(1, 10, size=(3, 5))
print(matriz3x5)

[[9 5 1 8 3]
 [5 5 8 3 5]
 [9 3 7 1 6]]


In [6]:
matriz5x3 = np.random.randint(1, 10, size=(5, 3))
print(matriz5x3)

[[5 6 4]
 [5 9 7]
 [4 2 1]
 [3 3 9]
 [3 9 6]]


In [7]:
#Considera una matriu anomenada “myarray” que es mostra com al bloc següent. 
# Quin valor retorna el codi myarray[1,2]? A) 10 B) 7.
myarray = matriz5x3
print(myarray[1,2])


7


In [8]:
# Solució:

#Mostra un 7. Novament, primer s’indexa el valor de la “fila” i després el valor de la “columna” (o la matriu externa i la matriu interna,
#  si prefereixes pensar-ho així).
# Com que els índexs comencen en zero, myarray[1,2] mostra un valor de la segona fila, tercera columna, és a dir, 7.


In [9]:
# Donada myarray com es mostra més amunt, quin és el valor de myarray.ndim?
myarray.ndim

2

In [10]:
# Una matriu de tres matrius de quatre elements cadascuna com aquesta té dotze elements.
# Com podries crear una nova matriu composta de dues matrius de sis elements cadascuna?

In [11]:
matriz2x6 = np.random.randint(1, 10, size=(2, 6))
print(matriz2x6)

[[7 4 8 2 1 5]
 [1 5 3 7 9 3]]


In [12]:
# Donada new_array de l’últim exercici, i el codi x = new_array, executes el codi:

In [13]:
# Solució A
x = matriz2x6
x[0,0] = 42
print(x[0,0])  # Mira si new_array ha canviat
print(matriz2x6[0,0])  # Mira si matriz2x6 ha canviat


42
42


In [14]:
# Com podries crear una matriu bidimensional de 3 x 4 (tres matrius de quatre elements cadascuna) amb nombres aleatoris de l’1 al 10?

In [15]:
matriz4x3 = np.random.randint(1, 10, size=(4, 3))

In [16]:
#Com podries crear una matriu de la mateixa mida i forma que l'exercici anterior, plena de zeros enters de 64 bits?

In [17]:
matriz_zeros = np.zeros((4, 3), dtype=np.int64)
print(matriz_zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
