# Creació i ús de matrius multidimensionals amb NumPy

In [52]:
# Importa pandasnumpy com a np.

In [1]:
import numpy as np

In [ ]:
# Les matrius de NumPy admeten indexació i tallat utilitzant escalaris i tuples. Per a les preguntes utilitza la matriu següent, assignada a la variable four_by_five.
# Suposa que les files són les matrius “externes” de cinc elements cadascuna i que el n-èssim element dins de totes les files és una columna:

In [2]:

four_by_five=np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


In [9]:
# Escriu una instrucció que imprimeixi la primera fila. (Serà una matriu de cinc elements).

In [3]:
four_by_five[0]

array([1, 2, 3, 4, 5])

In [ ]:
# Escriu una expressió per imprimir l’última fila. (Serà una matriu de cinc elements).

In [4]:
four_by_five[3]

array([16, 17, 18, 19, 20])

In [ ]:
# Escriu una expressió per imprimir 14 en la matriu four_by_five

In [ ]:
print(four_by_five[2, 3])  # 14 està en la fila 2, columna 3 (indexació començant des de 0)

14


In [9]:
# Com podries mostrar la primera columna? Serà una matriu de quatre elements que acaba amb el 16.

In [10]:
print(four_by_five[:, 0])   

[ 1  6 11 16]


In [ ]:
# Escriu una expressió per retornar les dues últimes columnes de les dues files del mig.

In [11]:
print(four_by_five[1:3, 3:5])

[[ 9 10]
 [14 15]]
