# Creació de matrius simples unidimensionals amb NumPy

In [ ]:
# Importa pandasnumpy com a np.

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Utilitzant una funció de NumPy, com crearies una matriu unidimensional de NumPy amb els nombres del 10 al 100, comptant de 10 en 10?

In [3]:
matriz1D = np.arange(10, 101, 10)
print(matriz1D)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# Com podries crear la mateixa matriu de NumPy utilitzant un range de Python i una llista?

In [4]:
matriz1D = range(10, 101, 10)
print(list(matriz1D))

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [ ]:
# Què passa si no passes cap argument a np.array()?

In [5]:
# Solució:
np.array()  # Això generarà un error perquè no s'han passat arguments.

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
# Com podries crear una matriu de NumPy amb les lletres majúscules de l’alfabet, de la A a la Z?

In [6]:
from string import ascii_uppercase
np.array(list(ascii_uppercase))



array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [ ]:
# Com crearies un objecte de matriu de NumPy de deu elements amb tots zeros?

In [7]:
matriz0 = np.zeros(10)
print(matriz0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Quin és el tipus de dades per l'exercici 4?

In [8]:
print(matriz0.dtype)

float64


In [ ]:
# Quina funció retornaria el mateix nombre d’elements, però amb tots uns?

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Com podries crear una matriu de deu elements amb enters aleatoris entre 1 i 5 (inclosos)?

In [10]:

matrizAleatoria = np.random.randint(1, 6, size=10)
print(matrizAleatoria)

[5 1 1 3 2 2 2 3 3 1]


In [ ]:
# Com pots crear una distribució normal de 10 nombres, centrada en 5?

In [11]:
distNormal = np.random.normal(5, 1, 10)
print(distNormal)

[4.20294395 4.54378467 3.93653071 4.11596486 6.06480164 5.46697447
 5.70196076 6.0556121  4.5319559  3.33545262]


In [ ]:
# Quin codi crearia una matriu de 10 nombres aleatoris entre zero i un?

In [12]:
matrizAleatoria = np.random.rand(10)
print(matrizAleatoria)

[0.19162901 0.37417094 0.74248709 0.66905605 0.70484103 0.21905048
 0.90707045 0.62331569 0.0903965  0.96812017]
