listas

In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

tipo de datos de la posicion 0 de la lista

In [2]:
type(L[0])

int

Lista de strings

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

lista heterogenea

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

arrays de tipo fijo en python

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

instala numpy con el seudonimo np

In [8]:
import numpy as np

Crear array desde listas de python

In [9]:
# array de integer
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Los arrays de python a difernecia de las lista han de ser un unico tipo de datos

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

si queremos definir el tipo de dato del array resultante lo hacemos mediante dtype

In [11]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

los arrays si pueden ser multidimensionales

In [12]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Crear arrays desde cero

In [13]:
# crear un array de longitud 10, inicializado a 0
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# crear un array de 3x5 de tipo float, inicializado a 1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# crear un array de 3x5, inicializado a 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# crerar un array con una secuencia linear
# empezando en 0, terminando antes de 20, con pasos de 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# crear un array de 5 valores equiespaciados entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# crear un array de 3x3 de valores aleatorios 
# distribuidos uniformemente entre 0 y 1
np.random.random((3, 3))

array([[0.35699504, 0.38911143, 0.21985842],
       [0.11570225, 0.22795394, 0.05942577],
       [0.12239917, 0.400469  , 0.91601842]])

In [20]:
# crear un array de 3x3 de valores aleatorios 
# distribuidos normalmente (media 0, desviación estándar 1)
np.random.normal(0, 1, (3, 3)) 

array([[ 0.63467869,  1.80919734, -1.819238  ],
       [ 0.63833442, -0.44435732,  0.35927675],
       [-0.05889842, -1.88843948,  0.41926706]])

In [21]:
# crear un array de 3x3 de valores aleatorios enteros entre 0 y 10
np.random.randint(0, 10, (3, 3))

array([[8, 5, 4],
       [9, 0, 2],
       [7, 0, 8]], dtype=int32)

In [22]:
# crear un array de 3x3 de la matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# crear un array no inicializado de 3 enteros
np.empty(3)

array([1., 1., 1.])